# Generated by Django 3.0.6 on 2020-05-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metrobus_history.District')),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Metrobus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=5, unique=True)),
                ('where_i_was', models.ManyToManyField(through='metrobus_history.HistoricalPoint', to='metrobus_history.Place')),
            ],
        ),
        migrations.AddField(
            model_name='historicalpoint',
            name='metrobus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrobus_history.Metrobus'),
        ),
        migrations.AddField(
            model_name='historicalpoint',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrobus_history.Place'),
        ),
    ]
