# Generated by Django 3.0.6 on 2020-05-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrobus_history', '0003_auto_20200526_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
